# Generated by Django 3.2.9 on 2021-12-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_mood_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social', models.CharField(blank=True, choices=[('reading', 'reading'), ('family', 'family'), ('friends', 'friends'), ('date', 'date'), ('party', 'party'), ('gaming', 'gaming'), ('sport', 'sport'), ('practice', 'practice'), ('healthy', 'healthy'), ('fast food', 'fast food'), ('restaurant', 'restaurant'), ('sweets', 'sweets'), ('exercise', 'exercise'), ('drink water', 'drink water'), ('walk', 'walk'), ('yoga', 'yoga'), ('shopping', 'shopping'), ('cooking', 'cooking'), ('cleaning', 'cleaning'), ('laundry', 'laundry')], max_length=20)),
                ('hobbies', models.CharField(blank=True, choices=[('reading', 'reading'), ('family', 'family'), ('friends', 'friends'), ('date', 'date'), ('party', 'party'), ('gaming', 'gaming'), ('sport', 'sport'), ('practice', 'practice'), ('healthy', 'healthy'), ('fast food', 'fast food'), ('restaurant', 'restaurant'), ('sweets', 'sweets'), ('exercise', 'exercise'), ('drink water', 'drink water'), ('walk', 'walk'), ('yoga', 'yoga'), ('shopping', 'shopping'), ('cooking', 'cooking'), ('cleaning', 'cleaning'), ('laundry', 'laundry')], max_length=20)),
                ('food', models.CharField(blank=True, choices=[('reading', 'reading'), ('family', 'family'), ('friends', 'friends'), ('date', 'date'), ('party', 'party'), ('gaming', 'gaming'), ('sport', 'sport'), ('practice', 'practice'), ('healthy', 'healthy'), ('fast food', 'fast food'), ('restaurant', 'restaurant'), ('sweets', 'sweets'), ('exercise', 'exercise'), ('drink water', 'drink water'), ('walk', 'walk'), ('yoga', 'yoga'), ('shopping', 'shopping'), ('cooking', 'cooking'), ('cleaning', 'cleaning'), ('laundry', 'laundry')], max_length=20)),
                ('health', models.CharField(blank=True, choices=[('reading', 'reading'), ('family', 'family'), ('friends', 'friends'), ('date', 'date'), ('party', 'party'), ('gaming', 'gaming'), ('sport', 'sport'), ('practice', 'practice'), ('healthy', 'healthy'), ('fast food', 'fast food'), ('restaurant', 'restaurant'), ('sweets', 'sweets'), ('exercise', 'exercise'), ('drink water', 'drink water'), ('walk', 'walk'), ('yoga', 'yoga'), ('shopping', 'shopping'), ('cooking', 'cooking'), ('cleaning', 'cleaning'), ('laundry', 'laundry')], max_length=20)),
                ('chores', models.CharField(blank=True, choices=[('reading', 'reading'), ('family', 'family'), ('friends', 'friends'), ('date', 'date'), ('party', 'party'), ('gaming', 'gaming'), ('sport', 'sport'), ('practice', 'practice'), ('healthy', 'healthy'), ('fast food', 'fast food'), ('restaurant', 'restaurant'), ('sweets', 'sweets'), ('exercise', 'exercise'), ('drink water', 'drink water'), ('walk', 'walk'), ('yoga', 'yoga'), ('shopping', 'shopping'), ('cooking', 'cooking'), ('cleaning', 'cleaning'), ('laundry', 'laundry')], max_length=20)),
            ],
        ),
    ]
