# Generated by Django 3.2.9 on 2021-12-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_activities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='chores',
            field=models.CharField(blank=True, choices=[('shopping', 'shopping'), ('cooking', 'cooking'), ('cleaning', 'cleaning'), ('laundry', 'laundry')], max_length=20),
        ),
        migrations.AlterField(
            model_name='activities',
            name='food',
            field=models.CharField(blank=True, choices=[('healthy', 'healthy'), ('fast food', 'fast food'), ('restaurant', 'restaurant'), ('sweets', 'sweets')], max_length=20),
        ),
        migrations.AlterField(
            model_name='activities',
            name='health',
            field=models.CharField(blank=True, choices=[('exercise', 'exercise'), ('drink water', 'drink water'), ('walk', 'walk'), ('yoga', 'yoga')], max_length=20),
        ),
        migrations.AlterField(
            model_name='activities',
            name='hobbies',
            field=models.CharField(blank=True, choices=[('reading', 'reading'), ('gaming', 'gaming'), ('sport', 'sport'), ('practice', 'practice')], max_length=20),
        ),
        migrations.AlterField(
            model_name='activities',
            name='social',
            field=models.CharField(blank=True, choices=[('family', 'family'), ('friends', 'friends'), ('date', 'date'), ('party', 'party')], max_length=20),
        ),
    ]
