# Generated by Django 3.2.9 on 2021-12-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_activities_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
